# Radiata Pine example

In [5]:
import numpy as np
import sys
import emcee
import scipy.special as sp

In [2]:
data = np.loadtxt('../examples/data/RadiataPine.dat')

In [3]:
print(data)

[[1.00e+00 3.04e+03 2.92e+01 2.54e+01]
 [2.00e+00 2.47e+03 2.47e+01 2.22e+01]
 [3.00e+00 3.61e+03 3.23e+01 3.22e+01]
 [4.00e+00 3.48e+03 3.13e+01 3.10e+01]
 [5.00e+00 3.81e+03 3.15e+01 3.09e+01]
 [6.00e+00 2.33e+03 2.45e+01 2.39e+01]
 [7.00e+00 1.80e+03 1.99e+01 1.92e+01]
 [8.00e+00 3.11e+03 2.73e+01 2.72e+01]
 [9.00e+00 3.67e+03 3.23e+01 2.90e+01]
 [1.00e+01 2.31e+03 2.40e+01 2.39e+01]
 [1.10e+01 4.36e+03 3.38e+01 3.32e+01]
 [1.20e+01 1.88e+03 2.15e+01 2.10e+01]
 [1.30e+01 3.67e+03 3.22e+01 2.90e+01]
 [1.40e+01 1.74e+03 2.25e+01 2.20e+01]
 [1.50e+01 2.25e+03 2.75e+01 2.38e+01]
 [1.60e+01 2.65e+03 2.56e+01 2.53e+01]
 [1.70e+01 4.97e+03 3.45e+01 3.42e+01]
 [1.80e+01 2.62e+03 2.62e+01 2.57e+01]
 [1.90e+01 2.90e+03 2.67e+01 2.64e+01]
 [2.00e+01 1.67e+03 2.11e+01 2.00e+01]
 [2.10e+01 2.54e+03 2.41e+01 2.39e+01]
 [2.20e+01 3.84e+03 3.07e+01 3.07e+01]
 [2.30e+01 3.80e+03 3.27e+01 3.26e+01]
 [2.40e+01 4.60e+03 3.26e+01 3.25e+01]
 [2.50e+01 1.90e+03 2.21e+01 2.08e+01]
 [2.60e+01 2.53e+03 2.53e

In [4]:
id = data[:,0]
y = data[:,1]
x = data[:,2]
z = data[:,3]

In [43]:
y[3,0]

3480.0

In [5]:
n = len(x)

In [6]:
# Ensure column vectors
y = y.reshape(n,1)
x = x.reshape(n,1)
z = z.reshape(n,1)

In [7]:
# CHECK THIS
x = x - np.mean(x)
z = z - np.mean(z)

In [8]:
r_0 = 0.06
s_0 = 6
Q_0 = np.diag([r_0, s_0])
Q_0

array([[0.06, 0.  ],
       [0.  , 6.  ]])

In [9]:
mu_0 = np.array([[3000], [185]])

In [10]:
a_0 = 6
b_0 = 4 * 300**2

In [40]:
mu_0.shape

(2, 1)

In [12]:
X = np.c_[np.ones((n, 1)), x] 
Z = np.c_[np.ones((n, 1)), z] 

In [13]:
M_x = X.T.dot(X) + Q_0
M_x

array([[ 4.20600000e+01, -1.84741111e-13],
       [-1.84741111e-13,  8.52738333e+02]])

In [14]:
M_z = Z.T.dot(Z) + Q_0
M_z

array([[ 4.20600000e+01, -2.45137244e-13],
       [-2.45137244e-13,  8.96064762e+02]])

In [15]:
R_x = np.eye(42) - X.dot(np.linalg.inv(M_x)).dot(X.T)

In [16]:
R_z = np.eye(42) - Z.dot(np.linalg.inv(M_z)).dot(Z.T)

In [25]:
ln_z_x = -0.5 * n * np.log(np.pi)
ln_z_x += 0.5 * a_0 * np.log(b_0)
ln_z_x += sp.gammaln(0.5*(n + a_0)) - sp.gammaln(0.5*a_0)
ln_z_x += 0.5 * np.log(np.linalg.det(Q_0)) - 0.5 * np.log(np.linalg.det(M_x))
F_x = mu_0.T.dot(Q_0).dot(mu_0 + np.linalg.inv(M_x).dot(Q_0).dot(mu_0) + 2.0 * np.linalg.inv(M_x).dot(X.T).dot(y))
#F_x = 0
ln_z_x += -0.5 * (n + a_0) * np.log(y.T.dot(R_x).dot(y) + F_x + b_0)
ln_z_x

array([[-321.55071477]])

In [24]:
ln_z_z = -0.5 * n * np.log(np.pi)
ln_z_z += 0.5 * a_0 * np.log(b_0)
ln_z_z += sp.gammaln(0.5*(n + a_0)) - sp.gammaln(0.5*a_0)
ln_z_z += 0.5 * np.log(np.linalg.det(Q_0)) - 0.5 * np.log(np.linalg.det(M_z))
F_z = mu_0.T.dot(Q_0).dot(mu_0 + np.linalg.inv(M_z).dot(Q_0).dot(mu_0) + 2.0 * np.linalg.inv(M_z).dot(Z.T).dot(y))
#F_z = 0
ln_z_z += -0.5 * (n + a_0) * np.log(y.T.dot(R_z).dot(y) + F_z + b_0)
ln_z_z

array([[-316.68416081]])

In [36]:
ln_z_z - ln_z_x

array([[4.86655396]])

In [35]:
np.exp(ln_z_z - ln_z_x)

array([[129.87259901]])

In [30]:
beta0_x = np.linalg.inv(M_x).dot(X.T.dot(y) + Q_0.dot(mu_0))
c0_x = y.T.dot(y) + mu_0.T.dot(Q_0).dot(mu_0) - beta0_x.T.dot(M_x).dot(beta0_x)

ln_z2_x = -0.5 * n * np.log(np.pi)
ln_z2_x += 0.5 * a_0 * np.log(b_0)
ln_z2_x += sp.gammaln(0.5*(n + a_0)) - sp.gammaln(0.5*a_0)
ln_z2_x += 0.5 * np.log(np.linalg.det(Q_0)) - 0.5 * np.log(np.linalg.det(M_x))

ln_z2_x += -0.5 * (n + a_0) * np.log(c0_x + b_0)
ln_z2_x

array([[-310.12828554]])

In [31]:
beta0_z = np.linalg.inv(M_z).dot(Z.T.dot(y) + Q_0.dot(mu_0))
c0_z = y.T.dot(y) + mu_0.T.dot(Q_0).dot(mu_0) - beta0_z.T.dot(M_z).dot(beta0_z)

ln_z2_z = -0.5 * n * np.log(np.pi)
ln_z2_z += 0.5 * a_0 * np.log(b_0)
ln_z2_z += sp.gammaln(0.5*(n + a_0)) - sp.gammaln(0.5*a_0)
ln_z2_z += 0.5 * np.log(np.linalg.det(Q_0)) - 0.5 * np.log(np.linalg.det(M_z))

ln_z2_z += -0.5 * (n + a_0) * np.log(c0_z + b_0)
ln_z2_z

array([[-301.70460213]])

In [37]:
ln_z2_z - ln_z2_x

array([[8.4236834]])

In [38]:
np.exp(ln_z2_z - ln_z2_x)

array([[4553.64551112]])

In [50]:
nchains = 10

In [51]:
tau_prior_mean = a_0 / b_0
tau_prior_std = np.sqrt(a_0) / b_0
tau_prior_mean, tau_prior_std

(1.6666666666666667e-05, 6.804138174397716e-06)

In [70]:
tau_prior_mean - 3.0*tau_prior_std

-3.7457478565264813e-06

In [53]:
pos_tau = tau_prior_mean + tau_prior_std * np.random.randn(nchains)
pos_tau

array([ 7.39187007e-06,  1.08345086e-05,  8.54835641e-06,  1.59383857e-05,
       -5.61941030e-06,  9.25714033e-06,  8.26535565e-06,  1.14104737e-05,
        2.01551228e-05,  2.48986363e-05])

In [55]:
pos_alpha = mu_0[0,0] + 1.0 / np.sqrt(tau_prior_mean * r_0) * np.random.randn(nchains)
pos_alpha

array([4837.27340574,  913.85727972, 3777.68079219, 3251.4538334 ,
       3164.01956058, 1935.52458506, 2554.46286628, 3375.62392695,
       2880.16076004, 3834.11153228])

In [56]:
pos_beta = mu_0[1,0] +  1.0 / np.sqrt(tau_prior_mean * s_0) * np.random.randn(nchains)
pos_beta

array([218.38622613, 110.18706435, 330.51855572,  34.46745184,
       140.71419648,  45.97814764, 236.01403485, 246.32016767,
        63.41561518, 112.97900728])

In [58]:
pos = np.c_[pos_alpha, pos_beta, pos_tau] 

In [59]:
pos.shape

(10, 3)

In [60]:
pos

array([[ 4.83727341e+03,  2.18386226e+02,  7.39187007e-06],
       [ 9.13857280e+02,  1.10187064e+02,  1.08345086e-05],
       [ 3.77768079e+03,  3.30518556e+02,  8.54835641e-06],
       [ 3.25145383e+03,  3.44674518e+01,  1.59383857e-05],
       [ 3.16401956e+03,  1.40714196e+02, -5.61941030e-06],
       [ 1.93552459e+03,  4.59781476e+01,  9.25714033e-06],
       [ 2.55446287e+03,  2.36014035e+02,  8.26535565e-06],
       [ 3.37562393e+03,  2.46320168e+02,  1.14104737e-05],
       [ 2.88016076e+03,  6.34156152e+01,  2.01551228e-05],
       [ 3.83411153e+03,  1.12979007e+02,  2.48986363e-05]])

In [67]:
pos[0]

array([4.83727341e+03, 2.18386226e+02, 7.39187007e-06])

In [62]:
t = np.random.randn(3)
t

array([ 1.43082163,  0.63408746, -0.15984191])

In [66]:
q, w, e = t
q, w, e

(1.4308216305656543, 0.6340874640655172, -0.15984191433065886)

In [7]:
ln_evidence_x = -310.15360598478964

In [8]:
ln_evidence_z = -301.44233980429595

In [7]:
ln_evidence_x = -310.1525497643574

In [8]:
ln_evidence_z = -301.44168064838254

In [ ]:
# a_0 = 3, b_0 = 2 * 300**2

In [12]:
ln_evidence_x = -310.11603987644287

In [13]:
ln_evidence_z = -301.7014144825633

In [17]:
ln_evidence_x = -310.1269508286002

In [ ]:
ln_evidence_z = -301.70073402975044

In [21]:
ln_evidence_z - ln_evidence_x

8.41462546495768

In [22]:
np.exp(ln_evidence_z - ln_evidence_x)

4512.585117006154

In [16]:
np.log(4553.65)

8.423684388158511

In [24]:
x_2d = np.array([1, 2])
x_2d

array([1, 2])

In [25]:
np.append(x_2d, [3])

array([1, 2, 3])

In [33]:
for i,j in enumerate(range(1, 5)):
    print(i,j)

0 1
1 2
2 3
3 4
